apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- broadcaster.yaml
- broadcaster-sealed-secret.yaml
images:
- name: IMAGE-PLACEHOLDER
  newName: epylkkan/gitops-broadcaster
  newTag: 09259766d3cfe1f620e9577b152f87724afef98b
