apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- wiki-deployment.yaml
- wiki-service.yaml
- wiki-cronjob.yaml
- wiki-horizontalpodautoscaler.yaml
images:
- name: WIKI-IMAGE
  newName: epylkkan/gitops-wiki
  newTag: 196737c5cd19b12da291ac8a8137129b6582fb2e
