apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- be-rollout.yaml
- be-service.yaml
- be-horizontalpodautoscaler.yaml
images:
- name: BACKEND-IMAGE
  newName: epylkkan/gitops-be
  newTag: 257dd0d4c96a16fe5aee8ac09c2a2fbbbcaf6191
