apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- be-rollout.yaml
- be-service.yaml
- be-horizontalpodautoscaler.yaml
images:
- name: IMAGE-PLACEHOLDER
  newName: epylkkan/gitops-be
  newTag: ad76aed028b3a1d14fdaeab4bebcdfb4149308ed
