name: dwk training backend 4.08 gitops app  
  
on:
  workflow_dispatch:
    branches:
      - master
    paths:
      - '**'
      - '.github/workflows/gitops-gha_be.yaml'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    #env:
    #   working-directory: backend
    steps:
    - run: cd backend
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2 
      with:
       push: true
       tags: epylkkan/gitops-be:${{ github.sha }}              

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: backend/manifests
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: backend/manifests
      run: |-
        ./kustomize edit set image BACKEND-IMAGE=epylkkan/gitops-be:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'backend/manifests/kustomization.yaml'
        message: New version release for gitops-be ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}